---
name: GNE Standard Tests
on: [push,pull_request]

jobs:
  std_tests:
    name: std_tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 'gne_tests' repository
        uses: actions/checkout@v4

      - name: Checkout 'gne_exercises' repository (actions/checkout doesn't work)
        run: ./gh_actions.sh

      - name: "List files and directories"
        run: |
          pwd
          ls -al .
          ls -al ..

      - name: Setup python
        uses: actions/setup-python@v5
        id: cp311
        with:
          python-version: '3.11'
          architecture: x64 

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Poetry virtualenv
        uses: actions/cache@v4
        id: cached-poetry-dependencies
        with:
          path: .venv
          key: venv-${{ runner.os }}-cache-${{ steps.cp311.outputs.version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Virtual Environment Dependencies
        run: poetry install -C gne_tests/
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: "List files and directories"
        run: |
          pwd
          ls -al .
          ls -al ..

      - name: View installed packages
        run: |
          poetry run python -m pip list

      - name: Run pylama on 'gne_tests' and 'gne_exercises'
        run: |
          poetry run pylama .
          poetry run pylama ../gne_exercises/

      - name: Run black on 'gne_tests' and 'gne_exercises'
        run: |
          poetry run black --check .
          poetry run black --check ../gne_exercises/

      - name: Per-lesson tests
        run: |
          poetry run pytest -s -v -x tests/

